import { Destination, Hotel, Room, Booking, Review, Favorite, Profile } from './supabase';

// Mock Destinations
export const mockDestinations: Destination[] = [
  {
    id: 'dest-1',
    name: 'Manila',
    region: 'NCR',
    description: 'The vibrant capital of the Philippines',
    image_url: 'https://images.unsplash.com/photo-1578127282290-4d4f76b27ece?w=500',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dest-2',
    name: 'Cebu',
    region: 'Visayas',
    description: 'Beach paradise and diving destination',
    image_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dest-3',
    name: 'Boracay',
    region: 'Western Visayas',
    description: 'World-renowned beach resort island',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dest-4',
    name: 'Davao',
    region: 'Mindanao',
    description: 'The City of Blooming Flowers',
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dest-5',
    name: 'Palawan',
    region: 'MIMAROPA',
    description: 'Island paradise and adventure destination',
    image_url: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500',
    created_at: new Date().toISOString(),
  },
];

// Mock Hotels
export const mockHotels: Hotel[] = [
  {
    id: 'hotel-1',
    name: 'Manila Bay Resort & Spa',
    description: 'Luxury 5-star resort overlooking Manila Bay with world-class amenities',
    destination_id: 'dest-1',
    address: '1223 Roxas Blvd',
    city: 'Manila',
    province: 'NCR',
    rating: 4.8,
    review_count: 342,
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Room Service', 'Air Conditioning'],
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800',
      'https://images.unsplash.com/photo-1618773928944-c7e16e50c1f7?w=800',
    ],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hotel-2',
    name: 'Cebu Sunset Beach Club',
    description: 'Beachfront resort with pristine white sand and crystal waters',
    destination_id: 'dest-2',
    address: '456 Mactan Beach',
    city: 'Cebu',
    province: 'Cebu',
    rating: 4.7,
    review_count: 298,
    amenities: ['Beach Access', 'Private Pool', 'Water Sports', 'Restaurant', 'Spa', 'Free WiFi'],
    images: [
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
      'https://images.unsplash.com/photo-1551632786-de41ec16a colonnade1?w=800',
      'https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=800',
    ],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hotel-3',
    name: 'Boracay Paradiso Hotel',
    description: 'Premier beachfront hotel with stunning sunset views',
    destination_id: 'dest-3',
    address: 'Station 1, Boracay Island',
    city: 'Malay',
    province: 'Aklan',
    rating: 4.9,
    review_count: 567,
    amenities: ['Beach Access', 'Private Pool', 'Restaurant', 'Bar', 'Spa', 'Water Sports', 'Smart TV'],
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      'https://images.unsplash.com/photo-1578127282290-4d4f76b27ece?w=800',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    ],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hotel-4',
    name: 'Davao Highland Resort',
    description: 'Mountain retreat with panoramic views of Davao City',
    destination_id: 'dest-4',
    address: '789 Mountain View Rd',
    city: 'Davao',
    province: 'Davao del Sur',
    rating: 4.6,
    review_count: 215,
    amenities: ['Parking', 'Restaurant', 'Gym', 'Free WiFi', 'Air Conditioning', 'Kitchenette'],
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1571896349842-b27cf17459c2?w=800',
      'https://images.unsplash.com/photo-1571145408850-c7ee66b46ac5?w=800',
    ],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hotel-5',
    name: 'Palawan Eco-Lodge',
    description: 'Sustainable beachfront resort with eco-friendly practices',
    destination_id: 'dest-5',
    address: 'Sabang Beach, Puerto Princesa',
    city: 'Puerto Princesa',
    province: 'Palawan',
    rating: 4.8,
    review_count: 445,
    amenities: ['Beach Access', 'Kitchen', 'Water Sports', 'Restaurant', 'Parking', 'Free WiFi'],
    images: [
      'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    ],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Rooms
export const mockRooms: Room[] = [
  // Manila Bay Resort & Spa Rooms
  {
    id: 'room-1',
    hotel_id: 'hotel-1',
    name: 'Deluxe Bay View Room',
    room_type: 'Deluxe',
    description: 'Spacious room with panoramic bay views and modern amenities',
    price_per_night: 5500,
    capacity: 2,
    amenities: ['Air Conditioning', 'WiFi', 'Smart TV', 'Mini Bar', 'Work Desk', 'Rain Shower'],
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1618773928944-c7e16e50c1f7?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'room-2',
    hotel_id: 'hotel-1',
    name: 'Suite Presidential',
    room_type: 'Suite',
    description: 'Luxurious suite with separate living area and premium services',
    price_per_night: 12000,
    capacity: 4,
    amenities: ['Air Conditioning', 'WiFi', 'Smart TV', 'Jacuzzi', 'Butler Service', 'Kitchen'],
    images: [
      'https://images.unsplash.com/photo-1595521624412-e3fb3ce9596f?w=800',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'room-3',
    hotel_id: 'hotel-1',
    name: 'Standard Room',
    room_type: 'Standard',
    description: 'Comfortable room ideal for business travelers',
    price_per_night: 3500,
    capacity: 2,
    amenities: ['Air Conditioning', 'WiFi', 'TV', 'Work Desk', 'En Suite Bathroom'],
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Cebu Sunset Beach Club Rooms
  {
    id: 'room-4',
    hotel_id: 'hotel-2',
    name: 'Beach Front Premium',
    room_type: 'Premium',
    description: 'Beachfront room with direct sand access and ocean views',
    price_per_night: 7500,
    capacity: 3,
    amenities: ['Air Conditioning', 'WiFi', 'Smart TV', 'Beach Access', 'Kitchenette', 'Balcony'],
    images: [
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
      'https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'room-5',
    hotel_id: 'hotel-2',
    name: 'Garden Room',
    room_type: 'Standard',
    description: 'Garden view room with tropical surroundings',
    price_per_night: 4500,
    capacity: 2,
    amenities: ['Air Conditioning', 'WiFi', 'TV', 'Balcony', 'En Suite Bathroom'],
    images: [
      'https://images.unsplash.com/photo-1551632786-de41ec16a400?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Boracay Paradiso Hotel Rooms
  {
    id: 'room-6',
    hotel_id: 'hotel-3',
    name: 'Beachfront Suite Deluxe',
    room_type: 'Suite',
    description: 'Magnificent beachfront suite with private plunge pool',
    price_per_night: 15000,
    capacity: 4,
    amenities: ['Air Conditioning', 'WiFi', 'Smart TV', 'Private Pool', 'Jacuzzi', 'Room Service'],
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      'https://images.unsplash.com/photo-1578127282290-4d4f76b27ece?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'room-7',
    hotel_id: 'hotel-3',
    name: 'Ocean View Deluxe',
    room_type: 'Deluxe',
    description: 'Deluxe room with stunning ocean and sunset views',
    price_per_night: 9000,
    capacity: 3,
    amenities: ['Air Conditioning', 'WiFi', 'Smart TV', 'Balcony', 'Mini Bar', 'Water Sports'],
    images: [
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    ],
    available: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Davao Highland Resort Rooms
  {
    id: 'room-8',
    hotel_id: 'hotel-4',
    name: 'Mountain View Cottage',
    room_type: 'Cottage',
    description: 'Cozy cottage with panoramic mountain and city views',
    price_per_night: 3800,
    capacity: 3,
    amenities: ['Air Conditioning', 'WiFi', 'Kitchenette', 'Balcony', 'Heater'],
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'room-9',
    hotel_id: 'hotel-4',
    name: 'Executive Room',
    room_type: 'Executive',
    description: 'Business-friendly room with workspace and conference facilities',
    price_per_night: 5200,
    capacity: 2,
    amenities: ['Air Conditioning', 'WiFi', 'Work Desk', 'Meeting Room Access', 'Smart TV'],
    images: [
      'https://images.unsplash.com/photo-1571145408850-c7ee66b46ac5?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Palawan Eco-Lodge Rooms
  {
    id: 'room-10',
    hotel_id: 'hotel-5',
    name: 'Eco Bungalow Beach',
    room_type: 'Bungalow',
    description: 'Sustainable bamboo bungalow with beach access',
    price_per_night: 4800,
    capacity: 2,
    amenities: ['Fan', 'WiFi', 'Beach Access', 'Outdoor Shower', 'Natural Materials'],
    images: [
      'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'room-11',
    hotel_id: 'hotel-5',
    name: 'Treehouse Suite',
    room_type: 'Suite',
    description: 'Unique treehouse suite with rainforest canopy views',
    price_per_night: 8500,
    capacity: 3,
    amenities: ['Natural Ventilation', 'WiFi', 'Balcony', 'Outdoor Deck', 'Eco-Friendly'],
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    ],
    available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Bookings
export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    user_id: 'user-123',
    room_id: 'room-1',
    check_in: new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    check_out: new Date(new Date().getTime() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    guests: 2,
    total_price: 38500,
    status: 'confirmed',
    special_requests: 'Early check-in requested',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'booking-2',
    user_id: 'user-123',
    room_id: 'room-4',
    check_in: new Date(new Date().getTime() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    check_out: new Date(new Date().getTime() + 37 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    guests: 3,
    total_price: 52500,
    status: 'pending',
    special_requests: 'High floor preferred',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'booking-3',
    user_id: 'user-456',
    room_id: 'room-6',
    check_in: new Date(new Date().getTime() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    check_out: new Date(new Date().getTime() - 23 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    guests: 4,
    total_price: 105000,
    status: 'completed',
    special_requests: null,
    created_at: new Date(new Date().getTime() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    user_id: 'user-456',
    hotel_id: 'hotel-3',
    booking_id: 'booking-3',
    rating: 5,
    comment: 'Absolutely stunning property! The beachfront location is unbeatable and the staff was incredibly helpful.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'review-2',
    user_id: 'user-789',
    hotel_id: 'hotel-1',
    booking_id: null,
    rating: 4,
    comment: 'Great hotel with excellent service. The bay view from the room was breathtaking.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'review-3',
    user_id: 'user-101',
    hotel_id: 'hotel-5',
    booking_id: null,
    rating: 5,
    comment: 'Amazing eco-friendly resort. Loved the sustainable practices and pristine beach. Will definitely come back!',
    created_at: new Date().toISOString(),
  },
];

// Mock Favorites
export const mockFavorites: Favorite[] = [
  {
    id: 'fav-1',
    user_id: 'user-123',
    hotel_id: 'hotel-3',
    created_at: new Date().toISOString(),
  },
  {
    id: 'fav-2',
    user_id: 'user-123',
    hotel_id: 'hotel-5',
    created_at: new Date().toISOString(),
  },
  {
    id: 'fav-3',
    user_id: 'user-456',
    hotel_id: 'hotel-1',
    created_at: new Date().toISOString(),
  },
];

// Mock Profiles
export const mockProfiles: Profile[] = [
  {
    id: 'user-123',
    full_name: 'Maria Santos',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    phone: '+63 9123456789',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-456',
    full_name: 'Juan Dela Cruz',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Juan',
    phone: '+63 9198765432',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-789',
    full_name: 'Rosa Mendoza',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rosa',
    phone: '+63 9165432109',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-101',
    full_name: 'Carlos Reyes',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    phone: '+63 9187654321',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Export all mock data together
export const allMockData = {
  destinations: mockDestinations,
  hotels: mockHotels,
  rooms: mockRooms,
  bookings: mockBookings,
  reviews: mockReviews,
  favorites: mockFavorites,
  profiles: mockProfiles,
};
